name: HyperBian CI/Release Build

run-name: |
  ${{ github.event_name == 'push' && format('🌱 Push build - {0}', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('👷 PR #{0} build - {1}', github.event.pull_request.number, github.event.pull_request.title) || '' }}
  ${{ github.event_name == 'repository_dispatch' && '🚀 Triggered HyperBian build' || '' }}
  ${{ github.event_name == 'workflow_dispatch' && '🚀 Manual triggered HyperBian build' || '' }}

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
  repository_dispatch:
    types: [ hyperion_push ]

env:
  PLATFORM: bookworm

jobs:
  image-builder:
    name: "HyperBian (${{ matrix.pi-gen.architecture }})"
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        pi-gen: [
          { branch: master, architecture: armhf },
          { branch: arm64,  architecture: arm64 }
        ]

    steps:
      - name: ⬇ Checkout HyperBian
        uses: actions/checkout@v4

      - name: 🔧 Prepare
        run: |
          echo "Suites: ${{ env.PLATFORM }}" >> "./stage-hyperbian/00-install-hyperion/files/hyperion.sources"
          echo "Architectures: ${{ matrix.pi-gen.architecture }}" >> "./stage-hyperbian/00-install-hyperion/files/hyperion.sources"

      - name: 👷 Build
        id: build
        uses: usimd/pi-gen-action@v1.10.0
        with:
          image-name: "HYPERBIAN=HyperBian-${{ env.PLATFORM }}-${{ matrix.pi-gen.architecture }}"
          hostname: 'HyperBian'
          disable-first-boot-user-rename: 1
          username: 'hyperion'
          password: 'ambientlight'
          enable-ssh: 1
          stage-list: stage0 stage1 stage2 ./stage-hyperbian
          verbose-output: true
          pi-gen-version: ${{ matrix.pi-gen.branch }}
          release: ${{ env.PLATFORM }}

      - name: 📦 Upload
        if: ${{ github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.HYPERBIAN }}
          path: pi-gen/deploy/*.zip
          retention-days: 1
        

#####################################
###### Publish GitHub Releases ######
#####################################

  github_publish:
    name: 🚀 Publish GitHub Releases
    if: ${{ github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch' }}
    needs: [ image-builder ]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout HyperBian
        uses: actions/checkout@v4

      - name: 📑 Read HyperBian template
        uses: markpatterson27/markdown-to-output@v1
        id: hyperbian_template
        with:
          filepath: ./.github/workflows/template.md

      - name: 💾 Artifact download
        uses: actions/download-artifact@v4
        with:
          pattern: HyperBian-*
          merge-multiple: true

      - name: 📦 Create release and upload image
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: HyperBian
          name: 'HyperBian'
          prerelease: false
          body: ${{ steps.hyperbian_template.outputs.body }}
          files: '*.zip'

      - name: 🧹 Cleanup
        uses: geekyeggo/delete-artifact@v5
        with:
          name: artifact-*
          failOnError: false
